Update

diff --git a/bin/xdg-screensaver b/bin/xdg-screensaver
--- a/bin/xdg-screensaver
+++ b/bin/xdg-screensaver
@@ -2,9 +2,18 @@
 
 case "$1" in
     lock)
-        i3lock
+        i3lock || true  # The true thing is so lxqt proceeds with locking, even if i3lock doesn't return 0 because it's already activated.
         ;;
-#    *)
-#        echo "$@" >> /tmp/xdg-screensaver-failed
-#        ;;
+    reset)
+        # VLC calls this every 30 seconds. 
+        # Most xdg-screensaver implementations will disable themselves here.
+        # I'll just tell LXQt it should wait a little longer before locking the screen,
+        #   since VLC never reactivates the screensaver.
+        dbus-send --dest=org.freedesktop.ScreenSaver --type=method_call /ScreenSaver org.freedesktop.ScreenSaver.SimulateUserActivity
+        # Of course, this won't work if the locking timeout is shorter than 30 seconds.
+        ;;
+    *)
+        echo "$(date +%Y%m%d%H%M%S) $@"
+        echo "$(date +%Y%m%d%H%M%S) $@" >> /tmp/xdg-screensaver-failed
+        ;;
 esac
