2020 update

diff --git a/shell/.scripts/power b/shell/.scripts/power
--- a/shell/.scripts/power
+++ b/shell/.scripts/power
@@ -17,8 +17,9 @@ call_ck() {
 }
 
 call() {
+    # Try calling xfce4-powermanager or anything like it before trying consolekit2 directly
     dbus-send --print-reply --dest=org.freedesktop.PowerManagement /org/freedesktop/PowerManagement "org.freedesktop.PowerManagement.$@" > /dev/null 2> /dev/null || {
-        echo "PowerManager failed"
+        echo "PowerManagement failed"
         case "$1" in
             Suspend) lock; call_ck Suspend boolean:true ;;
             Hibernate) lock; call_ck Hibernate boolean:true ;;
@@ -26,6 +27,23 @@ call() {
             Shutdown) call_ck Stop ;;
         esac
     }
+}
+
+close_programs() {
+    if ! command -v wmctrl 2> /dev/null; then
+        return 0
+    fi
+    wmctrl -l | cut -d ' ' -f 1 | xargs -L1 wmctrl -ic
+    local attempts=3
+    while [ "$attempts" -gt 0 -a "$(wmctrl -l | wc -l)" -gt 0 ]; do
+        sleep 0.5
+        local attempts="$(expr "$attempts" - 1)"
+    done
+    if [ "$(wmctrl -l | wc -l)" -gt 0 ]; then
+        i3-nagbar -t error -m "Some programs refuse to close. Close them manually and try again."
+        return 1
+    fi
+    return 0
 }
 
 input="$(rofi -dmenu -i -p 'Power' -no-custom << EOF
@@ -40,7 +58,8 @@ EOF
 
 sleep 0.5
 case "$input" in
-    Logout) i3-msg exit ;;
-    Lock) lock ;;
-    Suspend|Hibernate|Reboot|Shutdown) call "$input" ;;
+    Logout) close_programs && i3-msg exit ;;
+    Lock) lock ;;  # TODO: Can we tell the power manager to lock?
+    Suspend|Hibernate) call "$input" ;;
+    Reboot|Shutdown) close_programs && call "$input" ;;
 esac
